# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_webpage', '0004_ngsfeaturehg19chr20pos10000000_ngsfeaturehg19chr20pos20000000_ngsfeaturehg19chr20pos30000000_ngsfeat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputtext',
            old_name='input_text',
            new_name='input_coordinates_text',
        ),
        migrations.RemoveField(
            model_name='inputtext',
            name='input_text_file',
        ),
        migrations.RemoveField(
            model_name='inputtext',
            name='selected_db',
        ),
        migrations.RemoveField(
            model_name='inputtext',
            name='selected_input',
        ),
        migrations.AddField(
            model_name='inputtext',
            name='input_genes_text',
            field=models.TextField(blank=True),
        ),
    ]
