# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_webpage', '0007_auto_20160711_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputcoordinatestext',
            name='hg_version_text',
            field=models.TextField(blank=True),
        ),
    ]
