# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_webpage', '0009_ngsfeaturehg18_ngsfeaturehg18a1genes_ngsfeaturehg18a2genes_ngsfeaturehg18a3genes_ngsfeaturehg18a4gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputgenestext',
            name='hg_version_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inputcoordinatestext',
            name='checked_database_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inputcoordinatestext',
            name='input_coordinates_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inputgenestext',
            name='checked_database_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inputgenestext',
            name='input_genes_text',
            field=models.TextField(),
        ),
    ]
