# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_webpage', '0013_auto_20160810_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputcoordinatestext',
            name='search_option',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inputgenestext',
            name='search_option',
            field=models.TextField(blank=True),
        ),
    ]
