# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_webpage', '0014_auto_20160810_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputcoordinatestext',
            name='checked_database_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inputgenestext',
            name='checked_database_list',
            field=models.TextField(blank=True),
        ),
    ]
