# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_webpage', '0018_auto_20160824_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputKeggText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_kegg_text', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InputText',
        ),
    ]
