# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_webpage', '0019_auto_20160824_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.IntegerField()),
            ],
        ),
    ]
