# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-09 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_webpage', '0020_testnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestNumber',
        ),
    ]
