# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_webpage', '0021_delete_testnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputTCGAText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_tcga_text', models.TextField(blank=True)),
            ],
        ),
    ]
