# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_webpage', '0022_inputtcgatext'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtcgatext',
            name='tumor_name_text',
            field=models.TextField(blank=True),
        ),
    ]
